spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
    name: application

  # Config database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082
  servlet:
    context-path: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always